[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools>=41.2",
  "setuptools_scm",
  "wheel",
]

[tool.black]
line-length = 100
target-version = ['py38']
skip-string-normalization = true
