name: Upload xesmf to PyPI

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools setuptools-scm wheel twine check-manifest

      - name: Build tarball and wheels
        run: |
          python setup.py sdist
          python -m pip wheel . -w dist --no-deps

      - name: Test the artifacts
        run: |
          python -m check_manifest --verbose
          python -m twine check dist/*

      # FIXME: failing at the moment b/c we don't have PyPI ownership
      # - name: Publish
      #   env:
      #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      #   run: |
      #     python -m twine upload dist/*

      - name: upload artifacs
        uses: actions/upload-artifact@v3
        with:
          path: dist/*
